version: '3'

services:
  todo_db:
    image: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - pgtest:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todo_app:
    image: todo_image
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - todo_db
    environment:
      DATABASE_URL: postgresql://app_user:app_password@todo_db:5432/app_db

volumes:
  pgdata:
#  pgtest:
